### ISSUE TITLE
Doesn't build without adding `#define _POSIX_C_SOURCE 200809L` or `#define _GNU_SOURCE`

### ISSUE THREAD

**Issue by Azathothas** [aperezdc/dmon#16]
Hi, 
I wanted to package this for soar: https://github.com/pkgforge/soar

However, it doesn't build on alpine docker:

```bash
conf.c:188:25: error: use of undeclared identifier 'strdup'
  188 |             char *arg = strdup(dbuf_str(&argument));
      |                         ^
1 error generated.
make[1]: *** [Makefile:30: conf.o] Error 1
make[1]: *** Waiting for unfinished jobs....
util.c:421:2: warning: Building support for RLIMIT_RSS, this may not work on Linux 2.6+ [-W#warnings]
  421 | #warning Building support for RLIMIT_RSS, this may not work on Linux 2.6+
      |  ^
1 warning generated.
make[1]: Leaving directory '/tmp/tmp.w1URM0mWbv/TEMPREPO'
make: *** [Makefile:20: all-multicall-0] Error 2
```

If I add `#define _POSIX_C_SOURCE 200809L` or `#define _GNU_SOURCE` to https://github.com/aperezdc/dmon/blob/master/conf.c#L7
Then it builds successfully
